---
title: "ess_a3"
author: "Danielle Sclafani"
date: "11/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(lubridate)
```

## attaching the csv

```{r}
in_out_data <- read_csv(here("inflow_outflow.csv"))
```

## graphing inflow and outflow


```{r}
ggplot(data = in_out_data, aes(x=year, y =inflow)) + geom_point()+
  geom_point(aes(x= year, y = outflow)) +
  labs(x = "Year", y = "Volume of inflow and outflow (10^9 m^3)",
       title = "Inflow and Outflow")
```

```{r, fig.cap= "Figure 1.0 shows the change in input and output of groundwater from 2000 to 2050. The blue line shows the inputs of groundwater, and the red lines is reflective of the outputs of groundwater"}
inflow <- in_out_data %>% 
  filter(year %in% c("2000","2050")) %>%
  select(inflow, year)
  
outflow <- in_out_data %>% 
  filter(year %in% c("2000", "2050")) %>%
  select(outflow, year)

ggplot(data = inflow, aes(x= year, y = inflow )) + geom_line(color = "cyan4")+
  geom_point(color = "cyan4")+
  geom_line(data = outflow, aes(x=year, y = outflow), color = "red")+
  geom_point(data=outflow, aes(x=year, y = outflow), color = "red")+
  labs(x = "Year", y = "Volume of flow (10^9 m^3)",
       title = "Inputs and Outputs of Groundwater from 2000 to 2050")+
  theme(plot.title = element_text(hjust = 0.5))

```

### Showing the three scenarios of groundwater loss from three different starting points

```{r}
ggplot(data = in_out_data, aes(x = year, y = start_350)) + geom_col(fill="blue", alpha = 0.5)+
  geom_col(data = in_out_data, aes(x=year, y = start_190), fill = "red",
           alpha = 0.5)+
  geom_col(data = in_out_data, aes(x=year, y = start_550), fill = "green",
           alpha = 0.5)
```

```{r}

one <- ggplot(data = in_out_data, aes(x = year, y = start_350)) + geom_col(fill="blue")
two <- ggplot(data = in_out_data, aes(x = year, y = start_190)) + geom_col(fill="red")
three <- ggplot(data = in_out_data, aes(x = year, y = start_550)) + geom_col(fill="green")

```

par(mfrow = c(3,1))
ggplot(data = in_out_data, aes(x = year, y = start_350)) + geom_col(fill="blue")
ggplot(data = in_out_data, aes(x = year, y = start_190)) + geom_col(fill="red")
ggplot(data = in_out_data, aes(x = year, y = start_550)) + geom_col(fill="green")


```{r, fig.cap= "Figure 1.0: Volume of Available Groundwater in California from 2000-2050. This scenario assumes that the volume of available groundwater at the beginning of 2000 was 550x10^8 m^3"}

ggplot(data = in_out_data, aes(x = year, y = start_550)) + geom_col(fill="purple", alpha = 0.5)+
  labs(x = "", y = "",
       title = "Volume in 2000 of 550x10^9 m^3")+
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5))
  
```
```{r, fig.cap= "Figure 1.0: Volume of available groundwater in California from 2000-2050. The volume of available ground water at the beginning of 2000 is 350x10^9 m^3, as predicted by the Curmin study."}
ggplot(data = in_out_data, aes(x = year, y = start_350)) + geom_col(fill="blue", alpha = 0.5)+
  labs(x = "", y = "Volume of Groundwater (10^9 m^3)",
       title = "Volume in 2000 of 350x10^9 m^3")+
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5))

```

```{r}
ggplot(data = in_out_data, aes(x = year, y = start_190)) + geom_col(fill="red", alpha = 0.5)+
  labs(x = "Year", y = "",
       title = "Volume in 2000 of 190x10^9 m^3")+
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5))

```

```{r}
outflow_slope <- read_csv("outflow slope 0.173.csv")

as.date(outflow_slope$year)


class(outflow_slope$year)

start_350 <- outflow_slope %>% 
  select(year_new, "starting with 350")
```
```{r}
ggplot(data=start_350, aes(x=year_new, y ="starting with 350")) + geom_col()
```


